version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/angular/app-i18n'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/app-settings'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/components/basic-components'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/components/component-host'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/components/component-providers'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/components/component-queries'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/components/dynamic-content'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/components/lifecycle'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/dependency-injection'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/directives/app-attach-directive'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/directives/app-upload-directive'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/directives/attribute-directives'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/directives/directive-example'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/directives/structural-directives'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/events'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/ng-docker'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/pipes/custom-pipes'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/pipes/pure-impure'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/pipes/standard-pipes'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/plugins'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/plugins-core'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/angular/plugins-example'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/typescript/metadata-example'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/typescript/systemjs-example'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/webpack/code-splitting'
    update_schedule: 'live'
  - package_manager: 'javascript'
    directory: '/webpack/webpack-example'
    update_schedule: 'live'
